# DEPLOYMENT OF KAFKA-Server
apiVersion: apps/v1
kind: Deployment                        
metadata:
  name: kafka-broker0
spec:                                   
  replicas: 1
  selector:
    matchLabels:                       
      app: kafka
  template:                             
    metadata:                           
      labels:
        app: kafka   
        id: "0"                   
    spec:                               
      containers:
      - name: kafka
        image: confluentinc/cp-kafka                    
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181
        - name: KAFKA_ADVERTISED_HOST_NAME                
          value: kafka-service
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka-service:9092
        - name: KAFKA_BROKER_ID
          value: "0"
        - name: KAFKA_CREATE_TOPICS
          value: java-example-json:3:1            # topic name : partition : replica
---
# Service of KAFKA-Server
apiVersion: v1
kind: Service                        
metadata:
  name: kafka-service   
  labels:
    name: kafka             
spec:                                   
  selector:
      app: kafka 
      id: "0"                   
  ports:                            
    - protocol: TCP  
      port: 9092
      targetPort: 9092
      name: kafka-port  
