# DEPLOYMENT OF PG-ADMIN
apiVersion: apps/v1
kind: Deployment                        # what kind of configuration
metadata:
  name: pgadmin-deployment                # 1) metadata name of the deployment
  labels:
    app: pgadmin
spec:                                   # 2) specification for deployment
  replicas: 1
  selector:
    matchLabels:                        # selctor will connect all together with this key, value name
      app: pgadmin
  template:                             # template has its own metadata and spec section
    metadata:                           # and it all apply to a Pod
      labels:
        app: pgadmin                      # specify a label in form of key, value pair
    spec:                               # 2) specification or blueprint for pod (containers)
      containers:
      - name: pgadmin4
        image: dpage/pgadmin4                    # Docker hub image
        ports:
          - containerPort: 80
        env:
          - name: PGADMIN_DEFAULT_EMAIL
            value: "admin"
          - name: PGADMIN_DEFAULT_PASSWORD                
            value: "admin"
          - name: PGADMIN_PORT                           # 'car' Table create if doesnt exist 
            value: "80"
        tty: true
---
# Service of PG-ADMIN4
apiVersion: v1
kind: Service                        # what kind of configuration
metadata:
  name: pgadmin-service                
spec:                                   
  selector:
      app: pgadmin                    # this schould be the same like label from deployment and pod
  type: LoadBalancer
  ports:                            
    - protocol: TCP  
      port: 80
      targetPort: 80              # this port should match with the port of deployment
      nodePort: 30200
