apiVersion: v1
kind: Service                        # what kind of configuration
metadata:
  name: nginx-service                # 1) metadata name of the service
spec:                                   # 2) specification 
  selector:
      app: nginx                    # this key, value pair is connected to deploment labels
  ports:                            # other configuration between service and deployment is port
    - protocol: TCP  
      port: 80
      targetPort: 8080              # this port should match with the port of deployment
