apiVersion: apps/v1
kind: Deployment                        # what kind of configuration
metadata:
  name: nginx-deployment                # 1) metadata name of the deployment
  labels:
    app: nginx
spec:                                   # 2) specification for deployment
  replicas: 2
  selector:
    matchLabels:                        # selctor will connect all together with this key, value name
      app: nginx
  template:                             # template has its own metadata and spec section
    metadata:                           # and it all apply to a Pod
      labels:
        app: nginx                      # specify a label in form of key, value pair
    spec:                               # 2) specification or blueprint for pod (containers)
      containers:
      - name: nginx
        image: nginx:1.16
        ports:
        - containerPort: 8080
