# Deployment of Kafka Broker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: "172.17.0.3"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zoo1:2181"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_BROKER_ID
              value: "0"
          #  - name: KAFKA_CREATE_TOPICS
          #    value: java-example-json:3:1

# Service that will manage Kafka Broker
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    name: kafka
spec:
  ports:
  - protocol: TCP
    port: 9092
    targetPort: 9092
    name: kafka-port
  selector:
    app: kafka
  type: LoadBalancer